name: qoffa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.17
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-Black.ttf
          weight: 900

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/LeagueSpartan-Black.ttf
          weight: 900
