// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqX5uis9IHCYUEeKGryEeWBWkplk2sSE',
    appId: '1:195739454685:web:f18b59532bfa3c926ddf34',
    messagingSenderId: '195739454685',
    projectId: 'qoffa-58638',
    authDomain: 'qoffa-58638.firebaseapp.com',
    storageBucket: 'qoffa-58638.firebasestorage.app',
    measurementId: 'G-D047C9QVGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnT8Li3I7N3G-tl8ljBPcI2xDeamTVGHI',
    appId: '1:195739454685:android:ba658dfd936bf8666ddf34',
    messagingSenderId: '195739454685',
    projectId: 'qoffa-58638',
    storageBucket: 'qoffa-58638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYGURE7ddUzYmOVfpWmGQwm0G1G77dMg',
    appId: '1:195739454685:ios:dcb123e81e50456c6ddf34',
    messagingSenderId: '195739454685',
    projectId: 'qoffa-58638',
    storageBucket: 'qoffa-58638.firebasestorage.app',
    iosClientId: '195739454685-uispqvtmbrfrek8klpifbb217ugprmdr.apps.googleusercontent.com',
    iosBundleId: 'com.qoffa.qoffa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYGURE7ddUzYmOVfpWmGQwm0G1G77dMg',
    appId: '1:195739454685:ios:dcb123e81e50456c6ddf34',
    messagingSenderId: '195739454685',
    projectId: 'qoffa-58638',
    storageBucket: 'qoffa-58638.firebasestorage.app',
    iosClientId: '195739454685-uispqvtmbrfrek8klpifbb217ugprmdr.apps.googleusercontent.com',
    iosBundleId: 'com.qoffa.qoffa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqX5uis9IHCYUEeKGryEeWBWkplk2sSE',
    appId: '1:195739454685:web:b43a3893536297e76ddf34',
    messagingSenderId: '195739454685',
    projectId: 'qoffa-58638',
    authDomain: 'qoffa-58638.firebaseapp.com',
    storageBucket: 'qoffa-58638.firebasestorage.app',
    measurementId: 'G-Y0ZK97XZW4',
  );

}